### ISSUE TITLE
Error when deleting a single event in recurring series

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#65]
With the latest version, I can't delete a single event in a recurring event series anymore. I get this error message:

```
{"level":"error","message":"Unknown error: {\"stack\":\"PayloadTooLargeError: request entity too large\\n    at readStream (/usr/app/api/node_modules/raw-body/index.js:156:17)\\n    at getRawBody (/usr/app/api/node_modules/raw-body/index.js:109:12)\\n    at read (/usr/app/api/node_modules/body-parser/lib/read.js:79:3)\\n    at jsonParser (/usr/app/api/node_modules/body-parser/lib/types/json.js:135:5)\\n    at Layer.handle [as handle_request] (/usr/app/api/node_modules/express/lib/router/layer.js:95:5)\\n    at trim_prefix (/usr/app/api/node_modules/express/lib/router/index.js:328:13)\\n    at /usr/app/api/node_modules/express/lib/router/index.js:286:9\\n    at Function.process_params (/usr/app/api/node_modules/express/lib/router/index.js:346:12)\\n    at next (/usr/app/api/node_modules/express/lib/router/index.js:280:10)\\n    at urlencodedParser (/usr/app/api/node_modules/body-parser/lib/types/urlencoded.js:100:7)\",\"message\":\"request entity too large\",\"name\":\"PayloadTooLargeError\",\"expected\":36201,\"length\":36201,\"limit\":20480,\"type\":\"entity.too.large\"}","method":"DELETE","path":"/api/v1/caldav-events/repeated","tags":["UNKNOWN","REST"],"timestamp":"2022-08-29 10:57:27"}
```

**Comment by nibdo** [comment]
I have increased limit in new version, should fix this.
