### ISSUE TITLE
Cannot find homeUrl: CalDav

### ISSUE THREAD

**Issue by albsch** [nibdo/bloben-app#74]
I'm trying to connect another CalDav calendar, but something is not working with the discovery process. I get the following error:

```
{"level":"error","message":"Cannot connect to Dav server: {\"stack\":\"Error: cannot find homeUrl\\n    at /usr/app/api/node_modules/tsdav/dist/tsdav.cjs.js:1164:15\\n    at Generator.next (<anonymous>)\\n    at fulfilled (/usr/app/api/node_modules/tsdav/dist/tsdav.cjs.js:45:58)\\n    at runMicrotasks (<anonymous>)\\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\",\"message\":\"cannot find homeUrl\"}","tags":["REST","CALDAV"],"timestamp":"2022-09-22 08:43:54"}
```

I'm using something like the following URL:

> https://mail.example.com/CalDAV

With Thunderbird, the discovery process works and it discovers the correct endpoint after providing login credentials:

> https://mail.example.com/CalDAV/~username/Calendar/My%20Calendar/

What could be the issue here?

**Comment by nibdo** [comment]
What provider is it please?

Could you try to add URL as **https://mail.example.com** without /CALDAV?

**Comment by nibdo** [comment]
Might be fixed in 0.15.5 version

**Comment by albsch** [comment]
Still happening. It should be a CommuniGate Pro provider, I don't have access to it.
